GET http://localhost:4000/products 
###
GET http://localhost:4000/users
###
POST http://localhost:4000/register
Content-Type: application/json

{
    "email":"Mohan12@gmail.com",
    "password":"Admin@17823",
    "isAdmin":false
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "email":"Rishank12@gmail.com",
    "password":"Admin@17823"
}

# https://byte-adept-3456-2.onrender.com/